export const MexicoStates = [
    { value: 'AG', label: 'Aguascalientes' },
    { value: 'BC', label: 'Baja California' },
    { value: 'BS', label: 'Baja California Sur' },
    { value: 'CH', label: 'Chihuahua' },
    { value: 'CI', label: 'Ciudad de México' },
    { value: 'CL', label: 'Colima' },
    { value: 'CM', label: 'Campeche' },
    { value: 'CO', label: 'Coahuila' },
    { value: 'CS', label: 'Chiapas' },
    { value: 'CU', label: 'Chihuahua' },
    { value: 'DG', label: 'Durango' },
    { value: 'EM', label: 'Estado de México' },
    { value: 'GT', label: 'Guanajuato' },
    { value: 'GR', label: 'Guerrero' },
    { value: 'HG', label: 'Hidalgo' },
    { value: 'JA', label: 'Jalisco' },
    { value: 'MI', label: 'Michoacán' },
    { value: 'MO', label: 'Morelos' },
    { value: 'NA', label: 'Nayarit' },
    { value: 'NL', label: 'Nuevo León' },
    { value: 'OA', label: 'Oaxaca' },
    { value: 'PB', label: 'Puebla' },
    { value: 'QE', label: 'Querétaro' },
    { value: 'QR', label: 'Quintana Roo' },
    { value: 'SI', label: 'Sinaloa' },
    { value: 'SL', label: 'San Luis Potosí' },
    { value: 'SO', label: 'Sonora' },
    { value: 'TA', label: 'Tabasco' },
    { value: 'TB', label: 'Tamaulipas' },
    { value: 'TL', label: 'Tlaxcala' },
    { value: 'VE', label: 'Veracruz' },
    { value: 'YU', label: 'Yucatán' },
    { value: 'ZA', label: 'Zacatecas' }
  ];
  
  export const USAstates = [
    { value: 'AL', label: 'Alabama' },
    { value: 'AK', label: 'Alaska' },
    { value: 'AZ', label: 'Arizona' },
    { value: 'AR', label: 'Arkansas' },
    { value: 'CA', label: 'California' },
    { value: 'CO', label: 'Colorado' },
    { value: 'CT', label: 'Connecticut' },
    { value: 'DE', label: 'Delaware' },
    { value: 'FL', label: 'Florida' },
    { value: 'GA', label: 'Georgia' },
    { value: 'HI', label: 'Hawaii' },
    { value: 'ID', label: 'Idaho' },
    { value: 'IL', label: 'Illinois' },
    { value: 'IN', label: 'Indiana' },
    { value: 'IA', label: 'Iowa' },
    { value: 'KS', label: 'Kansas' },
    { value: 'KY', label: 'Kentucky' },
    { value: 'LA', label: 'Louisiana' },
    { value: 'ME', label: 'Maine' },
    { value: 'MD', label: 'Maryland' },
    { value: 'MA', label: 'Massachusetts' },
    { value: 'MI', label: 'Michigan' },
    { value: 'MN', label: 'Minnesota' },
    { value: 'MS', label: 'Mississippi' },
    { value: 'MO', label: 'Missouri' },
    { value: 'MT', label: 'Montana' },
    { value: 'NE', label: 'Nebraska' },
    { value: 'NV', label: 'Nevada' },
    { value: 'NH', label: 'New Hampshire' },
    { value: 'NJ', label: 'New Jersey' },
    { value: 'NM', label: 'New Mexico' },
    { value: 'NY', label: 'New York' },
    { value: 'NC', label: 'North Carolina' },
    { value: 'ND', label: 'North Dakota' },
    { value: 'OH', label: 'Ohio' },
    { value: 'OK', label: 'Oklahoma' },
    { value: 'OR', label: 'Oregon' },
    { value: 'PA', label: 'Pennsylvania' },
    { value: 'RI', label: 'Rhode Island' },
    { value: 'SC', label: 'South Carolina' },
    { value: 'SD', label: 'South Dakota' },
    { value: 'TN', label: 'Tennessee' },
    { value: 'TX', label: 'Texas' },
    { value: 'UT', label: 'Utah' },
    { value: 'VT', label: 'Vermont' },
    { value: 'VA', label: 'Virginia' },
    { value: 'WA', label: 'Washington' },
    { value: 'WV', label: 'West Virginia' },
    { value: 'WI', label: 'Wisconsin' },
    { value: 'WY', label: 'Wyoming' }
  ];
  